# Generated by Django 3.2.7 on 2021-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата контракта')),
                ('position', models.IntegerField(choices=[(0, 'Продавец'), (1, 'Старший продавец'), (2, 'Руководитель отдела продаж')], default=0, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
    ]
